name: org_chart
description: A flutter orgranizational chart with drag and drop, zoom and pan, search, collapse, expand, and easy customizations!
version: 4.2.2
repository: https://github.com/ahnaineh/org_chart
issue_tracker: https://github.com/ahnaineh/org_chart/issues
homepage: https://ahnaineh.github.io


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  custom_interactive_viewer: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
